require("sunwook.core.autopair")
require("sunwook.core.comment")
require("sunwook.core.alpha")
require("sunwook.core.git")
require("sunwook.core.gps")
require("sunwook.core.illuminate")
require("sunwook.core.indent")
require("sunwook.core.lsp")
require("sunwook.core.luasnips")
require("sunwook.core.nvim-cmp")
require("sunwook.core.nvim-tree")
require("sunwook.core.refactor")
require("sunwook.core.status-lualine")
require("sunwook.core.telescope")
require("sunwook.core.term")
require("sunwook.core.treesitter")
-- require("sunwook.core.lspkind")
-- require("sunwook.core.neorg")
-- require("sunwook.core.orgmode")
-- require("sunwook.core.project")
-- require("sunwook.core.todo-comments")
-- require("sunwook.core.trouble")
