-- -------------------------------------
-- which-key
-- -------------------------------------
require("which-key").setup({
	delay = 0,
	icons = {
		mappings = false,
		keys = {
			Up = "Up",
			Down = "Down",
			Left = "Left",
			Right = "Right",
			C = "Ctrl-",
			M = "Alt-",
			D = "Cmd-",
			S = "Shift-",
			CR = "Enter",
			Esc = "Esc",
			NL = "Enter",
			BS = "Backspace",
			Space = "Space",
			Tab = "Tab",
			ScrollWheelDown = "WheelDown",
			ScrollWheelUp = "WheelUp",
			F1 = "F1",
			F2 = "F2",
			F3 = "F3",
			F4 = "F4",
			F5 = "F5",
			F6 = "F6",
			F7 = "F7",
			F8 = "F8",
			F9 = "F9",
			F10 = "F10",
			F11 = "F11",
			F12 = "F12",
		},
		breadcrumb = ">",
		separator = "->",
	},
	spec = {
		{ "<leader>s", group = "[S]earch" },
		{ "<leader>S", group = "[S]ubstitute" },
		{ "<leader>b", group = "[B]uffer" },
		{ "<leader>T", group = "[T]oggle" },
		{ "<leader>l", group = "[L]sp & Diagnostic" },
		{ "<leader>g", group = "[G]it" },
		{ "<leader>p", group = "[P]roject" },
		-- { "<leader>d", group = "[D]ebug" },
	},
})
